/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.ManageAirliner.ManageAirliners;
import Business.TravelAgency;
import Interface.ManageAirliner.TravelAgentLoginJPanel;
import java.awt.CardLayout;

/**
 *
 * @author niramaykelkar
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private TravelAgency travelAgency;

    public MainJFrame() {
        initComponents();
        travelAgency = new TravelAgency();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        travelAgentBtn = new javax.swing.JButton();
        manageCustomerBtn = new javax.swing.JButton();
        managAirlinerBtn = new javax.swing.JButton();
        cardSequenceJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        travelAgentBtn.setText("Travel Agent");
        travelAgentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelAgentBtnActionPerformed(evt);
            }
        });
        controlPanel.add(travelAgentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 271, 160, -1));

        manageCustomerBtn.setText("Customer");
        manageCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerBtnActionPerformed(evt);
            }
        });
        controlPanel.add(manageCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 331, 160, -1));

        managAirlinerBtn.setText("Airliner");
        managAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managAirlinerBtnActionPerformed(evt);
            }
        });
        controlPanel.add(managAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 209, 160, -1));

        splitPane.setTopComponent(controlPanel);

        cardSequenceJPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        cardSequenceJPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(cardSequenceJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managAirlinerBtnActionPerformed
        // TODO add your handling code here:
        ManageAirliners manageAirliners = new ManageAirliners(travelAgency, cardSequenceJPanel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        cardSequenceJPanel.add("manageAirliners", manageAirliners);
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_managAirlinerBtnActionPerformed

    private void travelAgentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelAgentBtnActionPerformed
        // TODO add your handling code here:
        TravelAgentLoginJPanel travelAgentLoginJPanel=new TravelAgentLoginJPanel(travelAgency, cardSequenceJPanel);
        cardSequenceJPanel.add("TravelAgentLoginJPanel",travelAgentLoginJPanel);
        CardLayout cardLayout= (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_travelAgentBtnActionPerformed

    private void manageCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerBtnActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_manageCustomerBtnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardSequenceJPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton managAirlinerBtn;
    private javax.swing.JButton manageCustomerBtn;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton travelAgentBtn;
    // End of variables declaration//GEN-END:variables
}
