/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.Employee.Employee;
import Business.UserAccount.UserAccount;
import Business.Validation.DOBValidation;
import Business.Validation.EmailValidation;
import Business.Validation.NumberValidation;
import Business.Validation.PhoneNoValidation;
import Business.Validation.StringValidation;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author deekshakjahuria
 */
public class ViewDonorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Employee employee;
    /**
     * Creates new form ViewDonorJPanel
     */
    public ViewDonorJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        inputVerifiers();
        employee = userAccount.getEmployee();
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        jTextField2.setText(employee.getName());
        if(employee.getDob()!=null && employee.getAddress1()!=null && employee.getCity()!=null 
                && employee.getZipCode()!=null && employee.getOccupation()!=null &&
                employee.getEmailId()!=null && employee.getPhoneNumber()!=null
                )
        {
        dobTextField.setText(dateFormat.format(employee.getDob()));
        addressTextField.setText(employee.getAddress1());
        cityTextField.setText(employee.getCity());
        zipcodeTextField.setText(employee.getZipCode());
        occupationTextField.setText(employee.getOccupation());
        emailTextField.setText(employee.getEmailId());
        phoneNumberTextField.setText(employee.getPhoneNumber());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        name6 = new javax.swing.JLabel();
        manageEnt = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        zipcodeTextField = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        name7 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        occupationTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        name3 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name5.setText("City:");
        add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 194, 28));

        jTextField2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 180, -1));

        name6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name6.setText("Zipcode:");
        add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 194, 28));

        manageEnt.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        manageEnt.setText("Donor Details");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 281, -1));

        cityTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 180, -1));

        addressTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 180, -1));

        zipcodeTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        zipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTextFieldActionPerformed(evt);
            }
        });
        add(zipcodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 180, -1));

        name1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name1.setText("Address:");
        add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 194, 28));

        phoneNumberTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 180, -1));

        dobTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dobTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextFieldActionPerformed(evt);
            }
        });
        add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 180, -1));

        name7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name7.setText("Phone Number:");
        add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 194, 28));

        name2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name2.setText("Email Address:");
        add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 194, 28));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 50));

        occupationTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        occupationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationTextFieldActionPerformed(evt);
            }
        });
        add(occupationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 180, -1));

        saveBtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_save (1).png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 110, 40));

        name3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name3.setText("Date Of Birth:");
        add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 194, 28));

        emailTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 180, -1));

        name4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name4.setText("Occupation:");
        add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 194, 28));

        name.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        name.setText("Full Name:");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 194, 28));

        updateBtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_update.png"))); // NOI18N
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue-and-silver-stetoscope-40568.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void zipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void dobTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void inputVerifiers()
    {
        InputVerifier dobValidation = new DOBValidation();
        dobTextField.setInputVerifier(dobValidation);
        InputVerifier noValidation = new NumberValidation();
        zipcodeTextField.setInputVerifier(noValidation);
        InputVerifier phnValidation = new PhoneNoValidation();
        phoneNumberTextField.setInputVerifier(phnValidation);
        InputVerifier emailValidation = new EmailValidation();
        emailTextField.setInputVerifier(emailValidation);
        InputVerifier strValidation = new StringValidation();
        jTextField2.setInputVerifier(strValidation);
        addressTextField.setInputVerifier(strValidation);
        cityTextField.setInputVerifier(strValidation);
        occupationTextField.setInputVerifier(strValidation);
    }
    private void occupationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationTextFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try
            {
                DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                Date dobVal  = dateFormat.parse(dobTextField.getText());
                employee.setFirstName(jTextField2.getText());
                employee.setAddress1(addressTextField.getText());
                employee.setCity(cityTextField.getText());
                employee.setZipCode(zipcodeTextField.getText());
                employee.setOccupation(occupationTextField.getText());
                employee.setDob(dobVal);
                employee.setPhoneNumber(phoneNumberTextField.getText());
                employee.setEmailId(emailTextField.getText());
                if( addressTextField.getText().trim().isEmpty() ||
                cityTextField.getText().trim().isEmpty() ||
                occupationTextField.getText().trim().isEmpty() ||
                emailTextField.getText().trim().isEmpty() ||
                phoneNumberTextField.getText().trim().isEmpty() ||
                dobTextField.getText().trim().isEmpty() ||
                zipcodeTextField.getText().trim().isEmpty() )
                {
                    JOptionPane.showMessageDialog(null, "Please enter all the details");
                    return;
                }
                userAccount.setEmployee(employee);
            }
            catch(NumberFormatException nfe)
            {
                JOptionPane.showMessageDialog(this, "Enter valid details", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            catch(ParseException pe)
            {
                JOptionPane.showMessageDialog(this, "Enter Valid Date of Birth", "warning",JOptionPane.WARNING_MESSAGE);
                 return;
            }
                JOptionPane.showMessageDialog(null, "Details Updated Successfully", "success", JOptionPane.PLAIN_MESSAGE);
                updateBtn.setEnabled(true);
                saveBtn.setEnabled(false);
                jTextField2.setEnabled(false);
                dobTextField.setEnabled(false);
                addressTextField.setEnabled(false);
                cityTextField.setEnabled(false);
                zipcodeTextField.setEnabled(false);
                occupationTextField.setEnabled(false);
                emailTextField.setEnabled(false);
                phoneNumberTextField.setEnabled(false);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        // TODO add your handling code here:
        jTextField2.setEnabled(true);
        jTextField2.setEditable(true);
        dobTextField.setEnabled(true);
        dobTextField.setEditable(true);
        addressTextField.setEnabled(true);
        addressTextField.setEditable(true);
        phoneNumberTextField.setEditable(true);
        zipcodeTextField.setEnabled(true);
        zipcodeTextField.setEditable(true);
        occupationTextField.setEnabled(true);
        occupationTextField.setEditable(true);
        phoneNumberTextField.setEnabled(true);
        cityTextField.setEditable(true);
        cityTextField.setEnabled(true);
        emailTextField.setEditable(true);
        emailTextField.setEnabled(true);
        saveBtn.setEnabled(true);
        updateBtn.setEnabled(false); 
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField zipcodeTextField;
    // End of variables declaration//GEN-END:variables
}
