/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirliner;

import Business.Customer;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author niramaykelkar
 */
public class TicketIdCheckJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TicketIdCheckJPanel
     */
    private JPanel cardSequenceJPanel;
    private TravelAgency travelAgency;
    private Customer customer;
    public TicketIdCheckJPanel(TravelAgency travelAgency, JPanel cardSequenceJPanel) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.travelAgency = travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 13, 85, 35));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN TO VIEW TICKET");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 13, -1, 35));

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 108, 190, -1));

        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 100, -1, 39));

        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 146, -1, 39));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 154, 190, -1));

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 237, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        boolean isCustomerWithTicket = false;
        Customer isCustomer=null;
        boolean checkInDirectory=false;
        if (!userNameTextField.getText().equals("")&&!passwordTextField.getText().equals("")) {
            for (Customer customer : travelAgency.getCustomerDirectory()) {
                if (customer.getUserName().equals(userNameTextField.getText().trim()) && customer.getPassword().equals(passwordTextField.getText().trim())) {
                    checkInDirectory = true;
                    break;
                }
            }
            if (checkInDirectory) {
                for (Customer customer : travelAgency.getCustomerDirectory()) {
                if (customer.getUserName().equals(userNameTextField.getText().trim()) && customer.getTicket() != null) {
                    isCustomer=customer;
                    isCustomerWithTicket = true;
                    break;
                }
            }
            if (isCustomerWithTicket) {
                WelcomeJPanel welcomeJPanel = new WelcomeJPanel(cardSequenceJPanel, isCustomer);
                userNameTextField.setText("");
                passwordTextField.setText("");
                cardSequenceJPanel.add("WelcomeJPanel", welcomeJPanel);
                CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
                cardLayout.next(cardSequenceJPanel);

            } else {
                JOptionPane.showMessageDialog(null, "Sorry. No ticket exist with this customer ID");
                userNameTextField.setText("");
                passwordTextField.setText("");
            }
                
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter a valid Username/Password.");
                userNameTextField.setText("");
                passwordTextField.setText("");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please enter all the fields");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
