/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.Flight;
import Business.FlightSchedule;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moury
 */
public class UpdateFleetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateFleetJPanel
     */
    private JPanel CardSequenceJPanel;
    private Airliner airliner;
    private FlightSchedule fSched;
    

    UpdateFleetJPanel(JPanel CardSequenceJPanel, Airliner airliner, FlightSchedule fSched) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
        this.fSched = fSched;
        populateTable();
    }
    
    void populateTable(){
        
       DefaultTableModel dtm=(DefaultTableModel)tblUpdateFleet.getModel();
       ArrayList<Flight> array=new ArrayList<Flight>();
       for(Flight f: fSched.getFlightSchedDir())
       {
           if(f.getAirlinerName().equals(airliner.getAirlinerName()))
           {
               array.add(f);
           }
       }
       dtm.setRowCount(0);
       for( Flight flight : array )
       {
           Object[] row=new Object[7];
           row[0] = flight;
           row[1] = flight.getDepartTime();
           row[2] = flight.getArrivalTime();
           row[3] = flight.getDepartAirport();
           row[4]= flight.getArrivalAirport();
           row[5] = flight.getAirplane().getManufacture()+flight.getAirplane().getModelNum();
           row[6]= flight.getAirlinerName();
           dtm.addRow(row);
       }
        
        
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUpdateFleet = new javax.swing.JTable();
        BtnAddNewFlight = new javax.swing.JButton();
        BtnUpdateFlightDetails = new javax.swing.JButton();
        BtnDeleteFlight = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        tblUpdateFleet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline", "Flight No.", "From", "Departure Date", "Departure time", "To", "Arrival Date", "Arrival Time", "Duration", "Capacity", "Seat Price"
            }
        ));
        tblUpdateFleet.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblUpdateFleet);
        tblUpdateFleet.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BtnAddNewFlight.setText("Add New Flight");
        BtnAddNewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddNewFlightActionPerformed(evt);
            }
        });

        BtnUpdateFlightDetails.setText("Update Flight Details");
        BtnUpdateFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateFlightDetailsActionPerformed(evt);
            }
        });

        BtnDeleteFlight.setText("Delete Flight");
        BtnDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteFlightActionPerformed(evt);
            }
        });

        BtnBack.setText("<- Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAddNewFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnUpdateFlightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnDeleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 301, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddNewFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdateFlightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDeleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(BtnBack)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddNewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddNewFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddNewFlightActionPerformed

    private void BtnUpdateFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateFlightDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdateFlightDetailsActionPerformed

    private void BtnDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeleteFlightActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddNewFlight;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDeleteFlight;
    private javax.swing.JButton BtnUpdateFlightDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUpdateFleet;
    // End of variables declaration//GEN-END:variables
}
