/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.FlightSchedule;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author niramaykelkar
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerJPanel
     */
    private JPanel CardSequenceJPanel;
    private Airliner airliner;
    //private FlightSchedule flightSched;
    ViewAirlinerJPanel(JPanel CardSequenceJPanel, Airliner airliner) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
        txtAirlineName.setText(airliner.getAirlinerName());
        txtAirlineBase.setText(airliner.getBase());
        //this.flightSched = flightSched;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        txtAirlineBase = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSaveAirliner = new javax.swing.JButton();
        btnUpdAirliner = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Update Airline Detail");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setText("Airline Name:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setText("Airline Base:");

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSaveAirliner.setText("Save");
        btnSaveAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAirlinerActionPerformed(evt);
            }
        });

        btnUpdAirliner.setText("Update");
        btnUpdAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdAirlinerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(btnSaveAirliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAirlineBase, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtAirlineName)
                            .addComponent(btnUpdAirliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtAirlineBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveAirliner)
                    .addComponent(btnUpdAirliner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
//        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
//        CardSequenceJPanel.remove(this);
//        layout.previous(CardSequenceJPanel);
        
        CardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        Component[] comps = CardSequenceJPanel.getComponents();
        for(Component comp:comps)
            if (comp instanceof ManageAirlinersJPanel)
            {
                ManageAirlinersJPanel mp = (ManageAirlinersJPanel) comp;
                mp.populateTable();
            }
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdAirlinerActionPerformed
        // TODO add your handling code here:
        btnSaveAirliner.setEnabled(true);
        txtAirlineName.setEnabled(true);
        txtAirlineBase.setEnabled(true);
        btnUpdAirliner.setEnabled(false);
    }//GEN-LAST:event_btnUpdAirlinerActionPerformed

    private boolean airlinerPatternCorrect() {
       Pattern p = Pattern.compile("^[a-zA-Z\\s]*$");
       Matcher m = p.matcher(txtAirlineName.getText());
       boolean b = m.matches();
       System.out.println(b);
       return b;

    }
    
    private void btnSaveAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAirlinerActionPerformed
        // TODO add your handling code here:
        if (txtAirlineName.getText().equals("") || txtAirlineBase.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No blank field is allowed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
        else if(txtAirlineName.getText().length() > 25 || txtAirlineBase.getText().length() > 25){
             JOptionPane.showMessageDialog(null, "Character Limit Reached!!.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
        else if (!airlinerPatternCorrect()){
            JOptionPane.showMessageDialog(null, "Please enter valid data!!.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
        else
        {
            airliner.setAirlinerName(txtAirlineName.getText());
            airliner.setBase(txtAirlineBase.getText());
            JOptionPane.showMessageDialog(null, "Your Updated AirLiner is Saved!! :)");
            btnSaveAirliner.setEnabled(false);
            txtAirlineName.setEnabled(false);
            txtAirlineBase.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveAirlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaveAirliner;
    private javax.swing.JButton btnUpdAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAirlineBase;
    private javax.swing.JTextField txtAirlineName;
    // End of variables declaration//GEN-END:variables
}
