/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ApplicantRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ApplicantOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author moury
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceJPanel
     */
    private JPanel userProcessContainer;
    private ApplicantOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    
   

    public InsuranceJPanel() {
        initComponents();
        

     //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public InsuranceJPanel(JPanel userProcessContainer, UserAccount userAccount, ApplicantOrganization organization, Enterprise enterprise, EcoSystem business) {
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseInsuranceJButton = new javax.swing.JButton();
        viewInsuranceJButton = new javax.swing.JButton();
        verifyInsuranceJButton = new javax.swing.JButton();

        purchaseInsuranceJButton.setText("Purchase Insurance");
        purchaseInsuranceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseInsuranceJButtonActionPerformed(evt);
            }
        });

        viewInsuranceJButton.setText("View Insurance");
        viewInsuranceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInsuranceJButtonActionPerformed(evt);
            }
        });

        verifyInsuranceJButton.setText("Verify Insurance");
        verifyInsuranceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyInsuranceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchaseInsuranceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewInsuranceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verifyInsuranceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(574, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(purchaseInsuranceJButton)
                .addGap(18, 18, 18)
                .addComponent(viewInsuranceJButton)
                .addGap(18, 18, 18)
                .addComponent(verifyInsuranceJButton)
                .addContainerGap(467, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseInsuranceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseInsuranceJButtonActionPerformed
        // TODO add your handling code here:
        PurchaseInsuranceJPanel purchaseInsuranceJPanel = new PurchaseInsuranceJPanel(userProcessContainer, userAccount, organization,enterprise,business);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("PurchaseInsuranceJPanel", purchaseInsuranceJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_purchaseInsuranceJButtonActionPerformed

    private void viewInsuranceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInsuranceJButtonActionPerformed
        // TODO add your handling code here:
        ViewInsuranceJPanel viewInsuranceJPanel = new ViewInsuranceJPanel(userProcessContainer, userAccount, organization,enterprise,business);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ViewInsuranceJPanel", viewInsuranceJPanel);
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewInsuranceJButtonActionPerformed

    private void verifyInsuranceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyInsuranceJButtonActionPerformed
        // TODO add your handling code here:
//        VerifyInsuranceJPanel verifyInsuranceJPanel = new VerifyInsuranceJPanel(userProcessContainer, userAccount, organization,enterprise,business);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        userProcessContainer.add("VerifyInsuranceJPanel", verifyInsuranceJPanel);
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_verifyInsuranceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton purchaseInsuranceJButton;
    private javax.swing.JButton verifyInsuranceJButton;
    private javax.swing.JButton viewInsuranceJButton;
    // End of variables declaration//GEN-END:variables
}
