/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ApplicantRole;

/**
 *
 * @author moury
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceJPanel
     */
    public InsuranceJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseInsuranceJButton = new javax.swing.JButton();
        viewInsuranceJButton = new javax.swing.JButton();
        verifyInsuranceJButton = new javax.swing.JButton();

        purchaseInsuranceJButton.setText("Purchase Insurance");
        purchaseInsuranceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseInsuranceJButtonActionPerformed(evt);
            }
        });

        viewInsuranceJButton.setText("View Insurance");

        verifyInsuranceJButton.setText("Verify Insurance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchaseInsuranceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewInsuranceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verifyInsuranceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(574, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(purchaseInsuranceJButton)
                .addGap(18, 18, 18)
                .addComponent(viewInsuranceJButton)
                .addGap(18, 18, 18)
                .addComponent(verifyInsuranceJButton)
                .addContainerGap(467, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseInsuranceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseInsuranceJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseInsuranceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton purchaseInsuranceJButton;
    private javax.swing.JButton verifyInsuranceJButton;
    private javax.swing.JButton viewInsuranceJButton;
    // End of variables declaration//GEN-END:variables
}
