/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ApplicantRole;

import Business.EcoSystem;
import Business.Employee.Applicant;
import Business.Employee.Employee;
import Business.Employee.VitalSign;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ApplicantOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Validation.MainValidation;
import Business.Validation.NumberValidation;
import Business.WorkQueue.DoctorTestWorkRequest;
import Business.WorkQueue.DonorTestWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.ManagerWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class VitalSignToDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VitalSignToDoctorJPanel
     */
    private JPanel userProcessContainer;
    private ApplicantOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    private Applicant applicant;
    private DoctorOrganization doctorOrganization;
    public VitalSignToDoctorJPanel(JPanel userProcessContainer, UserAccount userAccount, ApplicantOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business=business;
        inputVerifier();
        //applicant=userAccount.getApplicant();
        applicant = new Applicant(userAccount.getEmployee());
        populateDoctorComboBx();
        populateRequestTable();
        //valueLabel.setText(enterprise.getName());

    }

    public void inputVerifier()
    {
        InputVerifier noValidation = new NumberValidation();
        heartRateTxtField.setInputVerifier(noValidation);
        pulseTxtField.setInputVerifier(noValidation);
        weightTxtField.setInputVerifier(noValidation);
        bldPreTxtField.setInputVerifier(noValidation);
    }
    
    public void populateDoctorComboBx()
    {
       try
       {
        doctorComboBx.removeAllItems();
        doctorOrganization =  MainValidation.getDoctorOrganization(business, userAccount);
   //    System.out.println("doctorOrganization"+doctorOrganization.getName());
       if(doctorOrganization!=null)
       {
        if(doctorOrganization.getUserAccountDirectory().getUserAccountList().isEmpty())
        {
        JOptionPane.showMessageDialog(null, "No doctors exists in our records as of now!","warning", JOptionPane.WARNING_MESSAGE);
         return;    
        }
         doctorComboBx.removeAllItems();
        for(UserAccount userAccount : doctorOrganization.getUserAccountDirectory().getUserAccountList())
        {
        doctorComboBx.addItem(userAccount);
        }   
       }
       }
       catch(NullPointerException npe)
       {
       JOptionPane.showMessageDialog(null, "Dcotor Organization exists in our records as of now!","warning", JOptionPane.WARNING_MESSAGE);
         return;       
       }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(!(request instanceof LabTestWorkRequest)&& !(request instanceof DonorTestWorkRequest) && !(request instanceof ManagerWorkRequest))
            {
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[2] = request.getStatus();
            String result = ((DoctorTestWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting For Doctor to respond" : result;
            model.addRow(row);
            }
            
            
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        heartRateTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bldPreTxtField = new javax.swing.JTextField();
        weightTxtField = new javax.swing.JTextField();
        pulseTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        problemTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        dctrNameLabel = new javax.swing.JLabel();
        doctorComboBx = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Send Vital Signs to your Doctor ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        heartRateTxtField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        heartRateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartRateTxtFieldActionPerformed(evt);
            }
        });
        add(heartRateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Blood Pressure:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Pulse:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Weight: (Pounds)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        bldPreTxtField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(bldPreTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, -1));

        weightTxtField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        weightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTxtFieldActionPerformed(evt);
            }
        });
        add(weightTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 100, -1));

        pulseTxtField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(pulseTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 100, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Heart Rate:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Problem Desc:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 120, -1));

        problemTxtField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        problemTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemTxtFieldActionPerformed(evt);
            }
        });
        add(problemTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 210, -1));

        workRequestJTable.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MESSAGE", "RECEIVER", "STATUS", "RESULT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 540, 210));

        dctrNameLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dctrNameLabel.setText("Select a doctor you wish to send data to:");
        add(dctrNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 340, 30));

        doctorComboBx.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        doctorComboBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(doctorComboBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 180, 40));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue-and-silver-stetoscope-40568.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void heartRateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartRateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartRateTxtFieldActionPerformed

    private void weightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTxtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserAccount docAccount = (UserAccount) doctorComboBx.getSelectedItem();
        double HearRate = Double.parseDouble(heartRateTxtField.getText());
        double BloodPressure = Double.parseDouble(bldPreTxtField.getText());
        int Pulse = Integer.parseInt(pulseTxtField.getText());
        double Weight = Double.parseDouble(weightTxtField.getText());
        String message = problemTxtField.getText();
        if( heartRateTxtField.getText().trim().isEmpty() ||
            bldPreTxtField.getText().trim().isEmpty() ||
            pulseTxtField.getText().trim().isEmpty() ||
            weightTxtField.getText().trim().isEmpty() ||
            problemTxtField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter all the details");
            return;
        }
        VitalSign vs =applicant.addVital();
        vs.setBloodPressure(BloodPressure);
        vs.setHeartRate(HearRate);
        vs.setPulse(Pulse);
        vs.setWeightInPounds(Weight);
        vs.setTimeStamp(new Date());
        DoctorTestWorkRequest request = new DoctorTestWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Request to Doctor");
        /*VitalSign vs1=request.addVital();
       vs1.setBloodPressure(BloodPressure);
        vs1.setHeartRate(HearRate);
        vs1.setPulse(Pulse);
        vs1.setWeightInPounds(Weight);*/
        ArrayList<VitalSign> vt = new ArrayList<>();
        vt.add(vs);
        request.setVitalSignList(vt);
                
       for (Network N : business.getNetworkList()) {
            
            
                for ( Enterprise e   : N.getEnterpriseDirectory().getEnterpriseList()) {
                    
                        e.setEnterpriseType(Enterprise.EnterpriseType.Hospital);    
                        if (e.getEnterpriseType().getValue().equals("Hospital"))
                    {
        Organization org = null;
        // enterprise=((Enterprise)EnterpriseComboBox.getSelectedItem( ));
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;
                break;
            }
        }

        if (org!=null){
            docAccount.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
                    }
                
            }
          }
        JOptionPane.showMessageDialog(null, "VitalSigns sent to Doctor successfully");
        heartRateTxtField.setText("");
        bldPreTxtField.setText("");
        pulseTxtField.setText("");
        weightTxtField.setText("");
        problemTxtField.setText("");
        populateRequestTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void problemTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_problemTxtFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bldPreTxtField;
    private javax.swing.JLabel dctrNameLabel;
    private javax.swing.JComboBox doctorComboBx;
    private javax.swing.JTextField heartRateTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField problemTxtField;
    private javax.swing.JTextField pulseTxtField;
    private javax.swing.JTextField weightTxtField;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
