/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAgentRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ApplicantOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.ApplicantRole.PurchaseInsuranceJPanel;

/**
 *
 * @author moury
 */
public class InsuranceFrontJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceFrontJPanel
     */
    private JPanel userProcessContainer;
    private ApplicantOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    public InsuranceFrontJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageOrdersJButton = new javax.swing.JButton();
        manageInsuranceJButton = new javax.swing.JButton();

        manageOrdersJButton.setText("Manage Orders");
        manageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJButtonActionPerformed(evt);
            }
        });

        manageInsuranceJButton.setText("Manage Insurances");
        manageInsuranceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInsuranceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageInsuranceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageOrdersJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(manageOrdersJButton)
                .addGap(53, 53, 53)
                .addComponent(manageInsuranceJButton)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrdersJPanel manageOrdersJPanel = new ManageOrdersJPanel(userProcessContainer, organization, enterprise, userAccount, business);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageOrdersJPanel", manageOrdersJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersJButtonActionPerformed

    private void manageInsuranceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInsuranceJButtonActionPerformed
        // TODO add your handling code here:
        ManageInsurancesJPanel manageInsurancesJPanel = new ManageInsurancesJPanel(userProcessContainer, organization, enterprise, userAccount, business);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageInsurancesJPanel", manageInsurancesJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInsuranceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageInsuranceJButton;
    private javax.swing.JButton manageOrdersJButton;
    // End of variables declaration//GEN-END:variables
}
