/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author niramaykelkar
 */
public class DonorDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorDetailsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    public DonorDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        //inputVerifiers();
        //receiverAccountNumber.setText(Donation.receiversAccountNumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageEnt = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        helpName = new javax.swing.JLabel();
        cardNoTextField = new javax.swing.JTextField();
        expiryDate = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        toAccntNumber = new javax.swing.JLabel();
        receiverAccountNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEnt.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt.setText("Donation Details");
        jPanel1.add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 202, -1));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 130, 60));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 130, 60));

        name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        name.setText("Name:");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 90, -1));
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 246, -1));

        helpName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        helpName.setText("Card Number:");
        jPanel1.add(helpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        cardNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNoTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cardNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 246, -1));

        expiryDate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        expiryDate.setText("Expiry Date(MM/YYYY)");
        jPanel1.add(expiryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));
        jPanel1.add(monthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 64, -1));
        jPanel1.add(yearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, 64, -1));

        amount.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        amount.setText("Enter Amount:");
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));
        jPanel1.add(amountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 246, -1));

        toAccntNumber.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        toAccntNumber.setText("Receiver Account Number");
        jPanel1.add(toAccntNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 183, -1));

        receiverAccountNumber.setEditable(false);
        receiverAccountNumber.setEnabled(false);
        receiverAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverAccountNumberActionPerformed(evt);
            }
        });
        jPanel1.add(receiverAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 196, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, -1));

        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1514, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void refresh()
    {
     cardNoTextField.setText("");
     monthTextField.setText("");
     yearTextField.setText("");
     amountTextField.setText("");
     nameTextField.setText("");
    }
    
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if( nameTextField.getText().trim().isEmpty() ||
            cardNoTextField.getText().length()>10 ||
            monthTextField.getText().length()>2 ||
            yearTextField.getText().length()>4 ||
            amountTextField.getText().length()<0 )
        {
            JOptionPane.showMessageDialog(null, "Details entered are not valid!", "warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try
        {
            int month = Integer.parseInt(monthTextField.getText());
            int year = Integer.parseInt(yearTextField.getText());
            if(month < 0 || month > 12)
            {
                JOptionPane.showMessageDialog(null, "Enter valid month!", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(year < 2019 || year > 2029)
            {
                JOptionPane.showMessageDialog(null, "Enter valid year!", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }

            DateFormat df = new SimpleDateFormat("EEE, MMM d, YYYY hh:mm aaa");
            Calendar cal = Calendar.getInstance();
            String ts = df.format(cal.getTime());

//            Donation donation = userAccount.getEmployee().addDonation();
//            //Donation donation1 = new Donation();
//            donation.setDonationAmount(amountTextField.getText());
//            donation.setDonationDate(ts);
//            donation.setDonorsAccountName(nameTextField.getText());
//            donation.setDonorsAccountNumber(cardNoTextField.getText());

            try
            {
//                DonationWorkRequest donReq = new DonationWorkRequest();
//                donReq.setDonation(donation);
//                donReq.setDonatedBy(userAccount.getUsername());
//                donReq.setSender(userAccount);
//                donReq.setRequestDate(new Date());
//                donReq.setMessage("Money Donated");
//                userAccount.getWorkQueue().getWorkRequestList().add(donReq);
//                UserAccount ua = getManagerAccount();
//                if(ua==null)
//                {
//                    JOptionPane.showMessageDialog(null, "Account does not exist", "warning",JOptionPane.WARNING_MESSAGE);
//                    userAccount.getWorkQueue().getWorkRequestList().remove(donReq);
//                    return;
//                }
//                if(ua!=null)
//                {
//                    donReq.setReceiver(ua);
//                    donReq.setResolveDate(new Date());
//                    ua.getWorkQueue().getWorkRequestList().add(donReq);
//                    donReq.setStatus("Completed");
//                    JOptionPane.showMessageDialog(null, "Donation was made successfully", "success",JOptionPane.PLAIN_MESSAGE);
//                }
//                else
//                {
//                    userAccount.getWorkQueue().getWorkRequestList().remove(donReq);
//                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Account does not exist!", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            refresh();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Data Inccorrect!", "warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        refresh();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void cardNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNoTextFieldActionPerformed

    private void receiverAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverAccountNumberActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cardNoTextField;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JLabel helpName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField receiverAccountNumber;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel toAccntNumber;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
