/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niramaykelkar
 */
public class ViewDonationHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDonationHistory
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public ViewDonationHistoryJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        donorNameField.setText(userAccount.getEmployee().getName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewDonHistry = new javax.swing.JLabel();
        donorName = new javax.swing.JLabel();
        donorNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewDonHistry.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewDonHistry.setText("View Donation History");
        add(viewDonHistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 400, -1));

        donorName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        donorName.setText("Full Name:");
        add(donorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 20));

        donorNameField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        donorNameField.setEnabled(false);
        donorNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorNameFieldActionPerformed(evt);
            }
        });
        add(donorNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, -1));

        historyTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Donated to", "Requested Date", "Donated Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(historyTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 420, 126));

        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)historyTable.getModel();
        model.setRowCount(0);
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
        {
            Object[] rowData = new Object[4];
            rowData[0] = request;
            rowData[1] = request.getSender().getEmployee().getName(); 
            rowData[2] = dateFormat.format(request.getRequestDate()); 
            rowData[3] = request.getResolveDate() == null ? null : dateFormat.format(request.getResolveDate()); 
            model.addRow(rowData);
        }
    }
    
    private void donorNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorNameFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel donorName;
    private javax.swing.JTextField donorNameField;
    private javax.swing.JTable historyTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel viewDonHistry;
    // End of variables declaration//GEN-END:variables
}
